### ISSUE TITLE
finalisation du notebook 01_couplage.ipynb

### ISSUE THREAD

**Issue by alexandrecuer** [seviprince/dromotherm#12]
y intégrer entre autre les éléments d'algorithmique et qu'il y ait une bonne fluidité de lecture

[logigramme_algorithme au format open office draw - y intégrer le test sur Tsor_dro > y ](https://github.com/seviprince/dromotherm/files/4904066/logigramme_algorithme.zip)

![logigramme_algorithme](https://user-images.githubusercontent.com/24553739/87170208-521ff180-c2d1-11ea-8b4d-c4900a85ac10.gif)

![modèle_bâtiment](https://user-images.githubusercontent.com/24553739/87172871-34ed2200-c2d5-11ea-892a-8f139caa0c32.jpg)

**Comment by seviprince** [comment]
D'accord. Ça sera fait.
Aussi, monsieur Benoit et moi, sommes penchés sur la modélisation de la prise en glace du sous sol aujourd'hui.  Je vais faire compléter le notebook avec aussi.

**Comment by alexandrecuer** [comment]
Il faut faire mûrir ce logigramme ....il n'est pas encore compréhensible...a le relire, je pense qu'il faut y intégrer des bouts de code dedans pour qu'on ait une vraie vision d'ensemble et de détails en même temps

**Comment by seviprince** [comment]
Bonjour monsieur,
Voici une proposition de logigramme.
![logigramme](https://user-images.githubusercontent.com/63263854/87531920-b278af80-c692-11ea-9ca1-7001cc5b6a66.PNG)

**Comment by alexandrecuer** [comment]
J'aurais bien vu quelque chose de plus autoporteur et complet comme ceci, avec des éléments de code....

![logigramme_algorithme_2](https://user-images.githubusercontent.com/24553739/87870969-0b0abe00-c9ad-11ea-9b25-776de72ad03b.gif)

le voilà en zip

[logigramme_algorithme.zip](https://github.com/seviprince/dromotherm/files/4943453/logigramme_algorithme.zip)

**Comment by seviprince** [comment]
Bien reçu.
Mais on pourrait rajouter un START et un END?

**Comment by alexandrecuer** [comment]
il y a les flèches pour lire le logigramme....
est-ce que START et END vont apporter quelque chose ? à part être dans les soit-disant canons de l'algorithmique
je dirais en plus qu'on n'est pas à END à proprement parler, l'étape dont on précise l'algorithmique sert à passer de i-1 à i

**Comment by alexandrecuer** [comment]
Je suis en train de modifier le notebook pour l'améliorer

**Comment by alexandrecuer** [comment]
@tous : pour essayer de clôturer cette issue avant de partir en vacances, j'ai essayé de finaliser le notebook décrivant le couplage....

faites moi passer vos remarques
2 illustrations au crayons sont très provisoires, je vais les mettre au propre...
on pourrait envisager à peu de frais de faire tourner le code dedans pour avoir quelques sorties en illustration et égayer le tout

https://github.com/seviprince/dromotherm/blob/master/01_couplage.ipynb

**Comment by seviprince** [comment]
Bonjour,

La dernier point Algorithme de résolution, il y a un souci d'indice du schéma de Euler explicite
```
Tsable(i)=Tsable(i-1)+step*dTsable(i-1)/dt =Tsable(i-1)+step*diff(i-1)
```

**Comment by alexandrecuer** [comment]
pourtant c'est ce qu'on fait dans le code

OK tu dois avoir raison c'est parce que j'appelle diff[i] quelque chose qui pour toi est diff[i-1] en fait je pense

**Comment by seviprince** [comment]
C'est ça. C'est juste un problème d’appellation

**Comment by alexandrecuer** [comment]
alors il faut que je modifie le code pour être cohérent...je le ferais ensuite....
Pour t'avancer un peu, je viens de te refaire l'illustration pour le schéma simplifié...je vais la mettre en ligne
ca donne celà 
![couplage2](https://user-images.githubusercontent.com/24553739/88302423-20ae1980-cd06-11ea-980b-416653f22cf9.png)
NON c'est faux l'échangeur est 
![couplage2_cc](https://user-images.githubusercontent.com/24553739/88366540-ae7f1880-cd89-11ea-9f7d-11d2128e5bf0.png)
à contre-courant, c'est celà :

**Comment by alexandrecuer** [comment]
voilà ce que donne le notebook en pdf...c'est quant même mieux pour l'impression

[01_couplage(10).pdf](https://github.com/seviprince/dromotherm/files/4970540/01_couplage.10.pdf)

**Comment by seviprince** [comment]
> alors il faut que je modifie le code pour être cohérent...je le ferais ensuite....
> Pour t'avancer un peu, je viens de te refaire l'illustration pour le schéma simplifié...je vais la mettre en ligne
> ca donne celà
> ![couplage2](https://user-images.githubusercontent.com/24553739/88302423-20ae1980-cd06-11ea-980b-416653f22cf9.png)

Bien reçu.
C'est toujours avec libre office que vous l'aviez fait?

**Comment by alexandrecuer** [comment]
Non ça cest avec gimp J'ai mis le fichier xcf ds le dossier imagesEnvoyé depuis mon smartphone Samsung Galaxy.




-------- Message d'origine --------
De : "> seviprince (par Internet, dépôt noreply@github.com)" <notifications@github.com> 
Date : 23/07/2020  17:47  (GMT+01:00) 
À : seviprince/dromotherm <dromotherm@noreply.github.com> 
Cc : Alexandre CUER <alexandre.cuer@cerema.fr>, Author <author@noreply.github.com> 
Objet : Re: [seviprince/dromotherm] finalisation du notebook 01_couplage.ipynb (#12)

**Comment by alexandrecuer** [comment]
on peut fermer cette issue vu que le notebook est bien remanié....
