### ISSUE TITLE
Bilan énergétique

### ISSUE THREAD

**Issue by seviprince** [seviprince/dromotherm#14]
Bonjour,
Je suis entrain de faire le bilan énergétique pour les 8 cas d'usage.
Je calcule donc:
```
Energie solaire totale reçue par le dromotherm
Energie captée par le dromotherm
Le taux de récupération
Consommation totale du bâtiment.
Energie perdue= Energie captée par le dromotherm-Consommation du bâtiment 
```
Sur les 8 cas de figure suivants, je me rends compte que c'est seulement sur le cas 2 que l'énergie captée par le dromotherl est supérieure aux besoins énergétiques du bâtiment.
![cas8](https://user-images.githubusercontent.com/63263854/87760056-80d92300-c80f-11ea-84a8-f7e52265b146.png)
![cas7](https://user-images.githubusercontent.com/63263854/87760060-820a5000-c80f-11ea-8d32-00765210930e.png)
![cas6](https://user-images.githubusercontent.com/63263854/87760062-820a5000-c80f-11ea-94e3-ec21d27a577e.png)
![cas5](https://user-images.githubusercontent.com/63263854/87760064-82a2e680-c80f-11ea-863f-159e4d35b2c6.png)
![cas4](https://user-images.githubusercontent.com/63263854/87760067-833b7d00-c80f-11ea-967a-a4ae69739c3f.png)
![cas3](https://user-images.githubusercontent.com/63263854/87760070-83d41380-c80f-11ea-8d72-a35aea6c023c.png)
![cas2](https://user-images.githubusercontent.com/63263854/87760072-83d41380-c80f-11ea-9012-69b5e8a8840f.png)
![cas1](https://user-images.githubusercontent.com/63263854/87760074-846caa00-c80f-11ea-8914-35d13236e73f.png)

**Comment by seviprince** [comment]
Les cas sont numérotés du bas vers le haut

**Comment by alexandrecuer** [comment]
Hello
à priori tu n'utilises pas la dernière version...avec Frédéric, on était parti du principe qu'on ne travaillait pas sur des kWh/m2 mais seulement des Kwh
de plus j'avais indiqué les surfaces et les volumes au niveau dromotherme et stockage
si tu as des difficultés à rejoindre ma version via un merge, il faut qu'on en parle pour voir les difficultés

**Comment by alexandrecuer** [comment]
sinon oui ta conclusion est juste : pour l'instant, il faut faire tourner le dromotherme toute l'année, c'est le seul bilan favorable, mais en pratique peut-être devrons nous asservir le fonctionnement au rayonnement extérieur, (plus de 250 W/m2) voire à la température de la couche de surface et le bilan sera encore moins bon...d'où la nécessité d'un bon contrôle commande auquel avec Frédéric nous sommes en train de réfléchir....et là il faudra probablement autre chose que du python pour piloter, probablement du C/C++

**Comment by seviprince** [comment]
Voici la dernière version. Le constat reste identique.


![cas8](https://user-images.githubusercontent.com/63263854/87766053-e382ec80-c818-11ea-918f-dfaced6a7767.png)
![cas7](https://user-images.githubusercontent.com/63263854/87766062-e4b41980-c818-11ea-8dcf-a3c57c099cb9.png)
![cas6](https://user-images.githubusercontent.com/63263854/87766065-e54cb000-c818-11ea-9f0e-fd1a2eda581e.png)
![cas5](https://user-images.githubusercontent.com/63263854/87766070-e5e54680-c818-11ea-954d-ac18876ff958.png)
![cas4](https://user-images.githubusercontent.com/63263854/87766073-e67ddd00-c818-11ea-8031-e618017cfc4a.png)
![cas3](https://user-images.githubusercontent.com/63263854/87766074-e67ddd00-c818-11ea-843d-9a83a6a1eae1.png)
![cas2](https://user-images.githubusercontent.com/63263854/87766076-e7167380-c818-11ea-9128-37f7a4f868ff.png)
![cas1](https://user-images.githubusercontent.com/63263854/87766078-e7167380-c818-11ea-8df0-aa439cc5ef6d.png)

J'ai enlevé certains tracés qui ne sont pas vraiment utiles pour mon rapport (diff).

**Comment by B-Stutz** [comment]
l'énergie fournie au bâtiment (Chauffage + ECS) = énergie fournie par le dromotherme (énergie incidente - pertes dromotherme) + énergie électrique fournie à la PAC - énergie perdue par le stockage.

Attention, en période transitoire (sur 1 année), la température du stockage peut évoluer. Il faudrait faire ces bilan sur un cycle convergé (simulation sur plusieurs années consécutives permettant d'atteindre une température stable du stockage entre 2 années)

J'ai montré à Prince les diagrammes de Sankey qui permettent de bien illustrer ces bilans d'énergie
