### ISSUE TITLE
automatisation de la documentation 

### ISSUE THREAD

**Issue by alexandrecuer** [seviprince/dromotherm#8]
@seviprince : Fébron, il faudrait que tu ailles dans l'onglet settings du repo et que tu changes la branche de publication
j'ai automatisé la mise à jour de la doc de la bibliothèque. Le process maintient ainsi une branche appelée github-pages ou gh-pages et il faut pointer vers elle....

![image](https://user-images.githubusercontent.com/24553739/86835672-ba39c200-c09c-11ea-80e9-f230ef366969.png)

![image](https://user-images.githubusercontent.com/24553739/86835551-924a5e80-c09c-11ea-8ec2-c5410010ae73.png)

**Comment by seviprince** [comment]
C'est fait

**Comment by alexandrecuer** [comment]
bizarre je ne parviens pas à retrouver les nouveaux fichiers produits par les robots...
STP, peux-tu me faire capture d'écran de la page que je vois le pointage....apparemment le message d'erreur est qu'il n'y a pas de répertoire /docs, mais çà c'était avant 
bonne nuit :-)

**Comment by seviprince** [comment]
Ça devrait marcher maintenant... 
![repo](https://user-images.githubusercontent.com/63263854/86846579-5965b600-c0ab-11ea-8711-e632c3c37611.PNG)

**Comment by alexandrecuer** [comment]
Non c'est pas la dedans qu'il faut faire des modifications
Il faut remettre master comme branche par défaut
C'est dans les options qu'il faut aller 
La tu es allé ds branches et pas dans options
On peut se faire un skype?

**Comment by seviprince** [comment]
D'accord.Je suis en ligne

**Comment by alexandrecuer** [comment]
Tout marche
